export default {
    // CASE_UPDATE: 'تحديث الحالة: ',
    // NEWEST_UPDATE: "أحدث تحديث",
    // CONFIRMED: "تم تأكيد",
    // RECOVERED: "تم الاسترداد",
    // DECEASED: "متوفى",
    // CORONAVIRUS: "فيروس كورونا",
    // SEARCH:"بحث",
    // SEARCH_BY_COUNTRY:"البحث حسب البلد"
    HOME: 'الصفحة الرئيسية',
    PROFILE_SCREEN_SHORT: "شاشة الملف الشخصي",
    PROFILE_SCREEN_CAP: "شاشة الملف الشخصي",
    PROFILE_SCREEN_2: "شاشة ملف التعريف 2",
    PROFILE_SCREEN_3: "شاشة ملف التعريف 3",
    CONTACT: "اتصل",
    CAMERA: "الة تصوير",
    LOGOUT: "تسجيل خروج",
    MAPSCREEN_SHORT:"شاشة الخريطة",
    MAPSCREEN_CAP:"شاشة الخريطة",
    REDUX:"إعادة",
    SIGN_IN:"تسجيل الدخول",
    SIGN_UP: "اشتراك",
    TEXT_1:"جديد هنا ؟ يسجل",
    TEXT_2:"مسجل بالفعل؟",
    EMAIL:"البريد الإلكتروني",
    PASSWORD:"كلمه السر",
    FIRSTNAME:"الاسم الأول",
    LASTNAME:"الكنية",
    INTERCEPTOR:"لمعترض",
    CREATE_ACTIVITY:"إنشاء نشاط",
    USERNAME:"اسم المستخدم",
    PHONE_NUMBER:"رقم الهاتف",
    CRUDSCREEN:"شاشة Crud"
  
  };
  