export default {
  // CASE_UPDATE: 'केस अपडेट: ',
  // NEWEST_UPDATE: "नवीनतम अद्यतन",
  // CONFIRMED: "पुष्टीकृत",
  // RECOVERED: "ठीक हुए",
  // DECEASED: "स्वर्गीय",
  // CORONAVIRUS: "कोरोनावाइरस",
  // SEARCH_BY_COUNTRY: "देश के आधार पर खोजें",
  // SEARCH: "खोजें",

  HOME: 'گھر',
  PROFILE_SCREEN_SHORT: 'پروفائل اسکرین',
  PROFILE_SCREEN_CAP: 'پروفائل اسکرین',
  PROFILE_SCREEN_2: 'پروفائل اسکرین 2',
  PROFILE_SCREEN_3: 'پروفائل اسکرین 3',
  CONTACT: 'رابطہ کریں۔',
  CAMERA: 'کیمرہ',
  LOGOUT: 'لاگ آوٹ',
  MAPSCREEN_SHORT: 'میپ اسکرین',
  MAPSCREEN_CAP: 'میپ اسکرین',
  REDUX: 'ریڈکس',
  SIGN_IN: 'سائن ان',
  SIGN_UP: 'سائن اپ',
  TEXT_1: 'یہاں نیا؟ رجسٹر کریں۔',
  TEXT_2: 'پہلے سے رجسٹرڈ ہے؟',
  EMAIL: 'ای میل',
  PASSWORD: 'پاس ورڈ',
  FIRSTNAME: 'پہلا نام',
  LASTNAME: 'آخری نام',
  INTERCEPTOR:"انٹرسیپٹر",
  CREATE_ACTIVITY:"سرگرمی بنائیں",
  USERNAME:"صارف کا نام",
  PHONE_NUMBER:"فون نمبر",
  CRUDSCREEN:"کروڈ اسکرین"
};
